export const alertHeader = [
    {title: "Patient Details", class:"w-[320px]"},
    {title: "Risk Profile", class:""},
    {title: "Core Plan Status", class:""},
    {title: "Patient Adherence", class:""},
    {title: "Latest Updates", class:""},
    {title: "Action", class:""},
  ];

export const alertData = [
    {
      patientId: "123456",
      patientName: "Arnold Marsh",
      riskProfile: "High for T2D",
      actionComplet: false,
      actionCount: 62,
    },
    {
      patientId: "123456",
      patientName: "Samanta Bullok",
      reason: "Inflated A1C",
      recentChanges: "New lab data received",
      riskProfile: "High for T2D",
      actionComplet: true,
      actionCount: null,
    },
    {
      patientId: "123456",
      patientName: "Stas Spark",
      reason: "Inflated A1C",
      recentChanges: "New lab data received",
      riskProfile: "High for T2D",
      actionComplet: false,
      actionCount: 42,
    },
    {
      patientId: "123456",
      patientName: "Tom Muller",
      reason: "Inflated A1C",
      recentChanges: "New lab data received",
      riskProfile: "High for T2D",
      actionComplet: true,
      actionCount: null,
    },
    {
      patientId: "123456",
      patientName: "Stas Spark",
      reason: "Inflated A1C",
      recentChanges: "New lab data received",
      riskProfile: "High for T2D",
      actionComplet: false,
      actionCount: 42,
    },
    {
      patientId: "123456",
      patientName: "Tom Muller",
      reason: "Inflated A1C",
      recentChanges: "New lab data received",
      riskProfile: "High for T2D",
      actionComplet: true,
      actionCount: null,
    },
    {
      patientId: "123456",
      patientName: "Stas Spark",
      reason: "Inflated A1C",
      recentChanges: "New lab data received",
      riskProfile: "High for T2D",
      actionComplet: false,
      actionCount: 42,
    },
    {
      patientId: "123456",
      patientName: "Tom Muller",
      reason: "Inflated A1C",
      recentChanges: "New lab data received",
      riskProfile: "High for T2D",
      actionComplet: true,
      actionCount: null,
    },
    {
      patientId: "123456",
      patientName: "Stas Spark",
      reason: "Inflated A1C",
      recentChanges: "New lab data received",
      riskProfile: "High for T2D",
      actionComplet: false,
      actionCount: 42,
    },
    {
      patientId: "123456",
      patientName: "Tom Muller",
      reason: "Inflated A1C",
      recentChanges: "New lab data received",
      riskProfile: "High for T2D",
      actionComplet: true,
      actionCount: null,
    },
    {
      patientId: "123456",
      patientName: "Stas Spark",
      reason: "Inflated A1C",
      recentChanges: "New lab data received",
      riskProfile: "High for T2D",
      actionComplet: false,
      actionCount: 42,
    },
    {
      patientId: "123456",
      patientName: "Tom Muller",
      reason: "Inflated A1C",
      recentChanges: "New lab data received",
      riskProfile: "High for T2D",
      actionComplet: true,
      actionCount: null,
    },
  ];